ethereum_rpc = "https://rpc.hoodi.ethpandaops.io"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.liquidity_drain_trap]
path = "out/LiquidityDrainTrap.sol/LiquidityDrainTrap.json"
response_contract = "0x01292b99F3F89a360F6bc17Fbab3c70283435a2c"
response_function = "respondCallback(uint256)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = ["0x16c5A04519C9C73fEE01A6D1CB15Aa0B9C36C8A6"]
address = "0xC6B6E01DBFCc35dd1DfA17E99983Ee996F6CD3FC"

